server.name: kibana
server.host: "0"
elasticsearch.url: http://192.168.200.130:9200 
elasticsearch.username: elastic
elasticsearch.password: changeme
xpack.monitoring.ui.container.elasticsearch.enabled: true 
#xpack.security.enabled: false
#xpack.grokdebugger.enabled: false
#xpack.graph.enabled: false
#xpack.ml.enabled: false
#xpack.monitoring.enabled: false
#xpack.reporting.enabled: false
