FROM docker.elastic.co/logstash/logstash:6.4.1
RUN rm -f /usr/share/logstash/pipeline/logstash.conf
#ADD pipeline/ /usr/share/logstash/pipeline/
#ADD config/ /usr/share/logstash/config/
#ADD plugins/ /usr/share/logstash/plugins/
#ADD data/ /usr/share/logstash/data/
ENV LS_HEAP_SIZE=2048m
