FROM centos:latest
ARG METRICBEAT_VERSION=6.2.4
ARG PACKETBEAT_VERSION=6.2.4
ARG WAZUH_AGENT_VERSION=3.3.1-1

RUN yum update -y
RUN yum install -y wget
RUN yum install -y curl
RUN yum install -y which
RUN yum install -y libpcap
RUN yum install -y net-tools
RUN curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-${METRICBEAT_VERSION}-x86_64.rpm
RUN rpm -Uvh metricbeat-${METRICBEAT_VERSION}-x86_64.rpm
COPY metricbeat.yml /etc/metricbeat/metricbeat.yml
#COPY docker.yml /etc/metricbeat/modules.d/docker.yml
COPY system.yml /etc/metricbeat/modules.d/system.yml

COPY logstash-forwarder.crt /etc/pki/tls/certs/logstash-forwarder.crt

RUN curl -L -O https://artifacts.elastic.co/downloads/beats/packetbeat/packetbeat-${PACKETBEAT_VERSION}-x86_64.rpm
RUN rpm -Uvh packetbeat-${PACKETBEAT_VERSION}-x86_64.rpm
COPY packetbeat.yml /etc/packetbeat/packetbeat.yml

COPY wazuh.repo /etc/yum.repos.d/wazuh.repo
RUN yum install -y wazuh-agent-${WAZUH_AGENT_VERSION} openscap-scanner
ADD register.sh /register.sh
RUN chmod +x /register.sh
COPY ossec.conf /var/ossec/etc/ossec.conf

ADD entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["start"]
